-- CREATE SCHEMA StayComm;

USE StayComm;

CREATE TABLE GUEST(
    GUEST_ID    INT UNSIGNED,
    GUEST_LNAME VARCHAR(64) NOT NULL,
    GUEST_FNAME VARCHAR(64) NOT NULL,
    GUEST_EMAIL VARCHAR(64) NOT NULL,
    GUEST_PHONE CHAR(10) NOT NULL,
    GUEST_PASSWORD  VARCHAR(64) NOT NULL,
    PRIMARY KEY (GUEST_ID)
);

ALTER TABLE GUEST
MODIFY COLUMN GUEST_PASSWORD VARCHAR(64) NOT NULL DEFAULT('NewPassword');


CREATE TABLE CREDIT_CARD(
    CREDIT_CARD_ID  INT UNSIGNED,
    CREDIT_CARD_NUM     CHAR(16) NOT NULL,
    CREDIT_CARD_EXP_DATE    CHAR(6) NOT NULL,
    CREDIT_CARD_CVV     CHAR(3) NOT NULL,
    GUEST_ID    INT UNSIGNED NOT NULL,
    PRIMARY KEY (CREDIT_CARD_ID),
    FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID)
);


INSERT INTO CREDIT_CARD(CREDIT_CARD_ID, CREDIT_CARD_NUM, CREDIT_CARD_EXP_DATE, CREDIT_CARD_CVV, GUEST_ID)
VALUES(1, 4733100977054323, '102024', 321, 100);

CREATE TABLE PROPERTY(
    PROPERTY_ID INT UNSIGNED,
    PROPERTY_NAME VARCHAR(64) NOT NULL,
    PROPERTY_STREET_ADDR VARCHAR(64) NOT NULL,
    PROPERTY_CITY VARCHAR(64) NOT NULL,
    PROPERTY_STATE CHAR(2) NOT NULL,
    PROPERTY_KING_ROOMS INT UNSIGNED NOT NULL,
    PROPERTY_QUEEN_ROOMS INT UNSIGNED NOT NULL,
    PRIMARY KEY (PROPERTY_ID)
);

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT UNSIGNED,
    EMPLOYEE_LNAME  VARCHAR(64) NOT NULL,
    EMPLOYEE_FNAME  VARCHAR(64) NOT NULL,
    EMPLOYEE_EMAIL  VARCHAR(64) NOT NULL,
    EMPLOYEE_PHONE  CHAR(10) NOT NULL,
    EMPLOYEE_PASSWORD   VARCHAR(64) NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

CREATE TABLE STAY(
    STAY_ID INT UNSIGNED,
    STAY_CHECKIN_DATE DATE NOT NULL,
    STAY_CHECKOUT_DATE DATE NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    GUEST_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (STAY_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID)
);

ALTER TABLE STAY
ADD STAY_IS_CHECKED_IN BOOLEAN NOT NULL DEFAULT FALSE;

ALTER  TABLE STAY
MODIFY COLUMN STAY_CHECKIN_DATE DATE NOT NULL;

ALTER TABLE STAY
MODIFY COLUMN STAY_CHECKOUT_DATE DATE NOT NULL;

CREATE TABLE ROOM(
    ROOM_ID INT UNSIGNED,
    ROOM_TYPE CHAR(1) NOT NULL,
    ROOM_IS_CLEAN BOOLEAN NOT NULL,
    ROOM_IS_BLOCKED BOOLEAN NOT NULL,
    STAY_ID INT UNSIGNED,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ROOM_ID),
    FOREIGN KEY (STAY_ID) REFERENCES STAY(STAY_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

CREATE TABLE RATE_PRICE(
    RATE_PRICE_ID INT UNSIGNED, 
    RATE_PRICE_PRICE DECIMAL(7,2) NOT NULL DEFAULT(99.0),
    RATE_DATE DATE NOT NULL,
    PRIMARY KEY (RATE_PRICE_ID)
);

ALTER TABLE RATE_PRICE
MODIFY COLUMN RATE_DATE DATE DEFAULT('1901-11-11');

INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_DATE) VALUES(1, '1901-11-11');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(2, 500.00, '2025-05-09');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(3, 500.00, '2025-05-10');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(4, 500.00, '2025-05-11');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(5, 500.00, '2025-06-27');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(6, 500.00, '2025-06-28');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(7, 500.00, '2025-06-29');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(8, 1022.00, '2025-10-22');
INSERT INTO RATE_PRICE(RATE_PRICE_ID, RATE_PRICE_PRICE, RATE_DATE) VALUES(9, 1000.00, '2025-10-21');


-- IF DATE DOESN'T MATCH ANY IN TABLE, DEFAULT TO RATE 1 --

CREATE TABLE STAY_RATE(
    STAY_ID INT UNSIGNED,
    RATE_PRICE_ID INT UNSIGNED DEFAULT(1),
    FOREIGN KEY (STAY_ID) REFERENCES STAY(STAY_ID),
    FOREIGN KEY (RATE_PRICE_ID) REFERENCES RATE_PRICE(RATE_PRICE_ID),
    PRIMARY KEY (RATE_PRICE_ID, STAY_ID)
);


ALTER TABLE ROOM
MODIFY COLUMN STAY_ID INT UNSIGNED UNIQUE;


ALTER TABLE STAY
MODIFY COLUMN STAY_IS_CHECKED_IN BOOLEAN DEFAULT NULL;





SELECT *
FROM ROOM;

SELECT *
FROM STAY;


UPDATE ROOM
SET STAY_ID = 172
WHERE ROOM_ID = 103;


INSERT INTO STAY_RATE(STAY_ID, RATE_PRICE_ID) VALUES(104, 1);

INSERT INTO STAY_RATE(STAY_ID, RATE_PRICE_ID) VALUES(105, 5);
INSERT INTO STAY_RATE(STAY_ID, RATE_PRICE_ID) VALUES(105, 6);
INSERT INTO STAY_RATE(STAY_ID) VALUES(105);
INSERT INTO STAY_RATE(STAY_ID, RATE_PRICE_ID) VALUES(106, 5);
INSERT INTO STAY_RATE(STAY_ID, RATE_PRICE_ID) VALUES(106, 6);
INSERT INTO STAY_RATE(STAY_ID) VALUES(106);

SELECT *
FROM STAY_RATE;



INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(101, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(103, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(105, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(107, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(109, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(111, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(113, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(115, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(117, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(119, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(121, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(123, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(125, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(127, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(129, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(131, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(133, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(135, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(137, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(139, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(141, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(143, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(145, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(147, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(149, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(201, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(203, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(205, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(207, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(211, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(213, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(215, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(217, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(219, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(221, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(223, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(225, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(227, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(229, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(231, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(233, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(235, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(237, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(239, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(241, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(243, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(245, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(247, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(249, 'K', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(251, 'K', TRUE, FALSE, 1);

INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(100, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(102, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(104, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(106, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(108, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(110, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(112, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(114, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(116, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(118, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(120, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(122, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(124, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(126, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(128, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(130, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(132, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(134, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(136, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(138, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(140, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(142, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(144, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(146, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(148, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(150, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(202, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(204, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(206, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(208, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(212, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(214, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(216, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(218, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(220, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(222, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(224, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(226, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(228, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(230, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(232, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(234, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(236, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(238, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(240, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(242, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(244, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(246, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(248, 'Q', TRUE, FALSE, 1);
INSERT INTO ROOM(ROOM_ID, ROOM_TYPE, ROOM_IS_CLEAN, ROOM_IS_BLOCKED, PROPERTY_ID)
VALUES(250, 'Q', TRUE, FALSE, 1);

SELECT *
FROM ROOM;

UPDATE ROOM
SET STAY_ID = NULL
WHERE STAY_ID in (172, 173, 174);

DELETE FROM STAY
WHERE STAY_ID = 121;

UPDATE STAY
SET ROOM_TYPE = 'K'
WHERE ROOM_TYPE = '';


SELECT *
FROM STAY;

SELECT *
FROM RATE_PRICE;

ALTER TABLE STAY
MODIFY COLUMN ROOM_TYPE CHAR(1) DEFAULT('K');

ALTER TABLE STAY
ADD COLUMN STAY_IS_CANCELED BOOLEAN DEFAULT(FALSE) NOT NULL;



INSERT INTO PROPERTY (PROPERTY_ID, PROPERTY_NAME, PROPERTY_STREET_ADDR, PROPERTY_CITY, PROPERTY_STATE, PROPERTY_KING_ROOMS, PROPERTY_QUEEN_ROOMS)
VALUES(1, 'Nickhill Suites', '100 Nicks House Lane', 'Nickville', "NP", 50, 50);

INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(100, 'Thegreat', 'Valtor', 'valtor@great.com', '4128675309', 'h00lah00ps');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(101, 'Connell', 'Stephanie', 'stephanie_thebest@gmail.com', '4125888000', '0$car122');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(102, 'Bonnet', 'Stede', 'gentleman@pirate.com', '8145018008', 'G0ld3arr!ng');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(103, 'Teach', 'Edward', 'blackbeard@pirate.com', '8145018009', 'M3rm4idFan18');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(104, 'Yi Sao', 'Zheng', 'queen@pirate.com', '5106093451', 'R3dC4pt4a!n');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(105, 'Hands', 'Izzy', 'first_mate@pirate.com', '6379750906', 'Un!c0rn24');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(106, 'Boodhari', 'Oluwande', 'teal_day@pirate.com', '8149838039', '0rang3H4t!');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(107, 'Jimenez', 'Jim', 'orange_knife@pirate.com', '8679014571', 'B00B53njo0y3r!');
INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(108, 'Banes', 'Richard', 'prince_ricky@pirate.com', '8573569034', 'r3alPr!nc3');


insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (109, 'Franzini', 'Coralyn', 'cfranzini30@uol.com.br', '6208074423', 'wK6,Ztcxj$');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (110, 'Colleck', 'Cleveland', 'ccolleck31@amazon.com', '8527743556', 'mZ9*lXEK5fQ!%F');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (111, 'Giacomo', 'Jackie', 'jgiacomo32@ezinearticles.com', '5669043372', 'rH3@Y8M=P6g}p?F9');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (112, 'Harber', 'Bar', 'bharber33@purevolume.com', '1173683554', 'fV4''@Lnrd&=IOJI');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (113, 'Laminman', 'Lianna', 'llaminman34@merriam-webster.com', '2817971778', 'pS3_PKbi9lZ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (114, 'Keattch', 'Randie', 'rkeattch35@vistaprint.com', '8249566083', 'uU8#?(P#9I0|');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (115, 'Threader', 'Phil', 'pthreader36@ebay.com', '3476084527', 'vK2"S*bFVF0*F''6`');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (116, 'Elderbrant', 'Penn', 'pelderbrant37@army.mil', '1912439541', 'pE9.EbI=Dj\nMTY');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (117, 'Dunniom', 'Merl', 'mdunniom38@google.com', '6415780949', 'zF7>mN|Oq_');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (118, 'Handes', 'Fitzgerald', 'fhandes39@mail.ru', '3846743391', 'dZ5=YS*g!gI');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (119, 'Flavelle', 'Vanni', 'vflavelle3a@senate.gov', '3726000008', 'vD0,=$ZE~'')Nw~');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (120, 'Cottill', 'Ave', 'acottill3b@fotki.com', '5433826337', 'mZ9#&782"J');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (121, 'Champion', 'Minna', 'mchampion3c@zimbio.com', '8685233606', 'nD4*$T.8|U');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (122, 'Hemshall', 'Syman', 'shemshall3d@gizmodo.com', '6439366899', 'fL1?qUb>qjYnE{O.');

insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (123, 'Chese', 'Pat', 'pchese3e@sitemeter.com', '8784616023', 'p00p333!');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (124, 'Dytham', 'Berny', 'bdytham3f@elegantthemes.com', '2565864039', 'vD8$mG=|AgBq@=\{');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (125, 'Jursch', 'Joycelin', 'jjursch3g@over-blog.com', '7804908782', 'zX3(um+u~y0');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (126, 'Heaffey', 'Bartholomeus', 'bheaffey3h@examiner.com', '3085150749', 'kF2)''?ea}\<c');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (127, 'Huckster', 'Carly', 'chuckster3i@123-reg.co.uk', '4772118021', 'pP7"~B''2rvB=2|');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (128, 'Bedminster', 'Susana', 'sbedminster3j@salon.com', '6415920957', 'lK4,aAJG`+PIW,vw');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (129, 'Breeds', 'Chastity', 'cbreeds3k@goo.gl', '4061517314', 'jU7.Y~ph06B');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (130, 'Mazdon', 'Edeline', 'emazdon3l@i2i.jp', '3062154877', 'vX1!sX/~xegF');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (131, 'Merrell', 'Rebecca', 'rmerrell3m@digg.com', '7365360294', 'qK7,N@dd{qLI');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (132, 'Mattevi', 'Erika', 'emattevi3n@joomla.org', '4066071292', 'rO4''GWg%A,');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (133, 'Sterrie', 'Alice', 'asterrie3o@ted.com', '1387148423', 'aE4&sBe&od%8G5N?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (134, 'Fydoe', 'Pandora', 'pfydoe3p@forbes.com', '6314395357', 'oZ0+_wS0Wd');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (135, 'Hainey`', 'Merola', 'mhainey3q@blinklist.com', '1723027208', 'uT3=~T3+k');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (136, 'Muggleton', 'Parrnell', 'pmuggleton3r@wordpress.com', '4492778567', 'zF6$''/L>_YuO');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (137, 'Beneteau', 'Jonah', 'jbeneteau3s@businessweek.com', '8388290145', 'uZ7}E''QN=|');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (138, 'Kowal', 'Cynde', 'ckowal3t@msn.com', '8349788240', 'gI5''_V3Q!h?eh');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (139, 'Wantling', 'Allard', 'awantling3u@nbcnews.com', '8347531000', 'tN5>b(OIt');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (140, 'Shiril', 'Alix', 'ashiril3v@devhub.com', '9697097503', 'lU9@Y|tIw%n');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (141, 'Delieu', 'Afton', 'adelieu3w@jimdo.com', '5803015426', 'iR3`20ucBI@!');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (142, 'Olyunin', 'Consuelo', 'colyunin3x@chron.com', '7545302875', 'lA8.7ae3r');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (143, 'Humbee', 'Juliet', 'jhumbee3y@barnesandnoble.com', '2723706550', 'rF8&*}<O');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (144, 'MacUchadair', 'Ami', 'amacuchadair3z@house.gov', '3517133861', 'rL3\8eQtGH2M');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (145, 'Signorelli', 'Alika', 'asignorelli40@smugmug.com', '5234532648', 'bE3+k=y\YFu,`');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (146, 'Mayor', 'Samara', 'smayor41@imdb.com', '2256589285', 'pB7*!}*vm/5');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (147, 'Lewerenz', 'Stevana', 'slewerenz42@macromedia.com', '4429852979', 'fI5?GYb@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (148, 'Dinsale', 'Thoma', 'tdinsale43@state.gov', '4453473997', 'gY7~`8cy7ik');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (149, 'Catlin', 'Torrin', 'tcatlin44@ox.ac.uk', '6194038413', 'qI2,UU//{M,,2T6');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (150, 'Cumine', 'Tiebout', 'tcumine45@latimes.com', '1311478950', 'iM0"j*<pjY{>?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (151, 'Kiehne', 'Carry', 'ckiehne46@narod.ru', '6017536855', 'jV9_#Q\S');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (152, 'Keedy', 'Morse', 'mkeedy47@sitemeter.com', '1935697889', 'tX5%D~_)B');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (153, 'Pearse', 'Edin', 'epearse48@google.co.jp', '4337595588', 'fZ4#%7''z%t');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (154, 'Spilling', 'Regan', 'rspilling49@geocities.com', '8305182425', 'hO9(UHM2q?d');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (155, 'Freed', 'Loree', 'lfreed4a@accuweather.com', '7504285088', 'rH4{ZZv0tA4A''Rhn');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (156, 'Hollingdale', 'Annetta', 'ahollingdale4b@pcworld.com', '8674597047', 'xD3+$5@FJA@&R#');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (157, 'Gaskamp', 'Dottie', 'dgaskamp4c@newsvine.com', '1432166477', 'qU4=l|ze');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (158, 'Fihelly', 'Gualterio', 'gfihelly4d@tripod.com', '9347235947', 'cD4.AULwM');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (159, 'Beauvais', 'Jarret', 'jbeauvais4e@house.gov', '4056624032', 'dY2%H%O5Cn5c');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (160, 'Dempsey', 'Phylis', 'pdempsey4f@sciencedirect.com', '8428242793', 'jR8>+%a1k');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (161, 'Filchakov', 'Sally', 'sfilchakov4g@addthis.com', '1678156745', 'dX0>cgk.7A?7(#');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (162, 'Lapley', 'Kennedy', 'klapley4h@ning.com', '6401496008', 'aV3`VZP%20');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (163, 'Pawley', 'Ram', 'rpawley4i@xrea.com', '8534623778', 'jR0?*N9/1P?yn,');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (164, 'Suero', 'Norean', 'nsuero4j@cbslocal.com', '9121468122', 'vA6#4|g*!Dns<@N');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (165, 'Bruhn', 'Drew', 'dbruhn4k@cdbaby.com', '3972230649', 'sJ1?QzXc!_j''3%%.');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (166, 'Penwright', 'Carie', 'cpenwright4l@prweb.com', '4936910695', 'bL5,SfT(5dy');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (167, 'Braden', 'Marie-jeanne', 'mbraden4m@amazonaws.com', '8991467133', 'wM1"yX|ZwhuJ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (168, 'Pickersgill', 'Carina', 'cpickersgill4n@berkeley.edu', '5728876221', 'sX7+4}Mgy');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (169, 'Latey', 'Odo', 'olatey4o@ovh.net', '3355982914', 'kI3.i9r\ZX');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (170, 'Groombridge', 'Ailyn', 'agroombridge4p@patch.com', '4764752208', 'lO7*jKG2Lb');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (171, 'Roizn', 'Talbot', 'troizn4q@google.com.br', '5981670148', 'eD3#ig7AIxc5X');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (172, 'Sherrin', 'Norman', 'nsherrin4r@prlog.org', '5859458235', 'jP9?j/?wqnq_');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (173, 'Nind', 'Alex', 'anind4s@baidu.com', '1398577965', 'hY2?U`\@U2E');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (174, 'Krolik', 'Keir', 'kkrolik4t@engadget.com', '1589891278', 'vF9<v0?D`2d0');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (175, 'Dillamore', 'Caz', 'cdillamore4u@huffingtonpost.com', '6361098520', 'mC0&Hkqu');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (176, 'Collaton', 'Mason', 'mcollaton4v@europa.eu', '1878875127', 'bO9=b1{|_kI0e');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (177, 'Blamphin', 'Farlie', 'fblamphin4w@usgs.gov', '1796199196', 'qC4*@n9n');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (178, 'Risdall', 'Melantha', 'mrisdall4x@ebay.com', '6999579615', 'yK3*\*BS');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (179, 'Fraschetti', 'Jillie', 'jfraschetti4y@usa.gov', '8892925357', 'eE1@V9''F,$&x|0}');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (180, 'Cod', 'Nelia', 'ncod4z@google.pl', '1444548373', 'qY4{u}|zF?n');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (181, 'Valois', 'Edita', 'evalois50@nasa.gov', '2814257795', 'pa$$w0rd');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (182, 'Madill', 'Yvette', 'ymadill51@goo.gl', '1584923307', 'wW8~xE~pB/');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (183, 'Silverton', 'Killy', 'ksilverton52@sourceforge.net', '2792843064', 'sO4''T|yvt!');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (184, 'Gable', 'Stan', 'sgable53@ucsd.edu', '1159919624', 'iN9}a1n''$N#*L&H');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (185, 'Conklin', 'Cosme', 'cconklin54@flavors.me', '3746470520', 'qR6=h7o$''/');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (186, 'Wahncke', 'Emery', 'ewahncke55@eventbrite.com', '8074280192', 'qT4|=hf$LB$ec`mc');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (187, 'Adamiec', 'Cherilyn', 'cadamiec56@google.ru', '9181084958', 'qB9?sa<Z_"yV0');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (188, 'Nehlsen', 'Flory', 'fnehlsen57@mayoclinic.com', '1037255453', 'pL5>+8Rs?\\~v}!B');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (189, 'Vecard', 'Anette', 'avecard58@bing.com', '5564522994', 'bA0{cXHM$o}w%9!v');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (190, 'Wherton', 'Daffi', 'dwherton59@twitpic.com', '7675616034', 'iG5}u(mWY!wL');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (191, 'Corbett', 'Stace', 'scorbett5a@usgs.gov', '3072926114', 'iD0}0p<f*NQZh');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (192, 'Bonifas', 'Jimmie', 'jbonifas5b@earthlink.net', '7246562121', 'sG9?o=rREl(t_iS');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (193, 'Tourot', 'Karlee', 'ktourot5c@washington.edu', '6733644452', 'sW2&@x8AJ,3x');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (194, 'Friett', 'Newton', 'nfriett5d@bloomberg.com', '4969313435', 'bU5''YGM$1n0K$3G#');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (195, 'Crocker', 'Cyrille', 'ccrocker5e@nymag.com', '2397897181', 'sZ3*29YKe$"}');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (196, 'Bodycote', 'Emera', 'ebodycote5f@liveinternet.ru', '2576237954', 'cC6@f(_k{n5');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (197, 'Hrycek', 'Lorens', 'lhrycek5g@adobe.com', '7325490900', 'fY5/A?)U@ecl');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (198, 'Conkie', 'Alvy', 'aconkie5h@unc.edu', '5035647416', 'dX0"9,rJzTW+D$s');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (199, 'McGoldrick', 'Frances', 'fmcgoldrick5i@yandex.ru', '2335368413', 'nZ5>sD}2o@Qo(S');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (200, 'Robilart', 'Diena', 'drobilart5j@irs.gov', '5243886187', 'mS0)%dPVw');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (201, 'Bostock', 'Halie', 'hbostock5k@ocn.ne.jp', '2785298655', 'lB5*MI"zk=e');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (202, 'McKibben', 'Hazlett', 'hmckibben5l@opera.com', '6731869708', 'rQ5}%8*_d$');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (203, 'Jacob', 'Heloise', 'hjacob5m@google.com', '1079959368', 'aM1@Jj@lNaj');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (204, 'Pledger', 'Alva', 'apledger5n@cam.ac.uk', '4545915996', 'zU5>uJ5''');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (205, 'Kenrick', 'Jose', 'jkenrick5o@mapy.cz', '7113723690', 'mL1+hW=drms@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (206, 'Bottrill', 'Arv', 'abottrill5p@yale.edu', '9313111836', 'yW9\9ry#<u');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (207, 'Stones', 'Pedro', 'pstones5q@deliciousdays.com', '9934662308', 'iV3/{@ySEnww');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (208, 'Kenward', 'Caesar', 'ckenward5r@amazon.co.uk', '7702517651', 'lT8+_weo>ph?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (209, 'Johnston', 'Claribel', 'cjohnston5s@goo.gl', '6268413059', 'wO8}JQ>bkEDU+');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (210, 'Sheldrick', 'Bev', 'bsheldrick5t@mayoclinic.com', '8684842748', 'eV0)_M''dD,ZX=TB(');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (211, 'Dann', 'Florie', 'fdann5u@archive.org', '7027409922', 'sG0~y/1YGSIc2');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (212, 'Aleswell', 'Gianni', 'galeswell5v@hugedomains.com', '6091608711', 'gO6\IM2qF');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (213, 'Pashbee', 'Faustina', 'fpashbee5w@tmall.com', '7358110374', 'hR1{y1drVo(');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (214, 'Shwenn', 'Monro', 'mshwenn5x@is.gd', '9832676508', 'pL4#9!\v(TsC*bZ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (215, 'Baxstar', 'Wake', 'wbaxstar5y@amazon.de', '6984435169', 'zX2?6!GCQ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (216, 'Weigh', 'Aili', 'aweigh5z@ow.ly', '7315194939', 'vA9"VWJ*g|"');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (217, 'Ludlem', 'Gib', 'gludlem60@t-online.de', '3553572469', 'kD1|@izg_9U!fyX');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (218, 'Williamson', 'Hussein', 'hwilliamson61@surveymonkey.com', '1779278467', 'pW7\ltWV8Gr!');

insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (219, 'Fedorski', 'Theresina', 'tfedorski62@joomla.org', '3837064691', 'fM2+Bfja');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (220, 'Renvoys', 'Larine', 'lrenvoys63@macromedia.com', '2207197066', 'qQ0(Pj45@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (221, 'Farrans', 'Andrei', 'afarrans64@over-blog.com', '7243017066', 'xW4>huc35ueeZ''');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (222, 'Manvelle', 'Sandro', 'smanvelle65@webeden.co.uk', '7656879428', 'iI3>$x%C~m*O$');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (223, 'Graffin', 'Joyann', 'jgraffin66@issuu.com', '5105514642', 'qL7,P9=z');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (224, 'Haggath', 'Gerome', 'ghaggath67@fastcompany.com', '3626277213', 'nC7''!~e8SFI&l~it');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (225, 'Halegarth', 'Martie', 'mhalegarth68@storify.com', '3143416193', 'qX6~UFUW|90');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (226, 'Lilford', 'Wyn', 'wlilford69@meetup.com', '5541808564', 'lR0/!Zc$3');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (227, 'Martinie', 'Briny', 'bmartinie6a@nymag.com', '1311693629', 'kN5#GM7pdsOA');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (228, 'Yakovl', 'Nikolaos', 'nyakovl6b@tmall.com', '5563484529', 'xJ5$Z?{+vD`Wl');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (229, 'Boost', 'Kirstyn', 'kboost6c@goodreads.com', '1826748333', 'iH6\276~vSV23');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (230, 'Raitt', 'Gayla', 'graitt6d@edublogs.org', '8161581889', 'bQ8/e)5"');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (231, 'Saladino', 'Vanya', 'vsaladino6e@comcast.net', '3056288256', 'sX9.%zDg@z3Z#1sZ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (232, 'Castiglio', 'Irving', 'icastiglio6f@acquirethisname.com', '8119405805', 'aL1?YM?.XK');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (233, 'Grieger', 'Dylan', 'dgrieger6g@unc.edu', '4169074980', 'gB7&NqoLlICM');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (234, 'Riddoch', 'Aharon', 'ariddoch6h@aol.com', '3612812428', 'sC9}eObl_');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (235, 'Considine', 'Alick', 'aconsidine6i@list-manage.com', '1584178901', 'zL6>uxaHc');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (236, 'Scalera', 'Eloisa', 'escalera6j@marriott.com', '1084385604', 'pQ4%g>.$)qCo');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (237, 'MacTrusty', 'Jacquette', 'jmactrusty6k@ibm.com', '1961722696', 'vV4/aX=HG0s@@b');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (238, 'Inchley', 'Mariel', 'minchley6l@mail.ru', '7623137268', 'aV4.xfTQHA?6+');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (239, 'Scheu', 'Thorin', 'tscheu6m@google.com.br', '1496425974', 'vB6%?''@9@M>#o');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (240, 'Floch', 'Marillin', 'mfloch6n@cyberchimps.com', '2595947587', 'hO0)FuxQWejJn');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (241, 'Sola', 'Kev', 'ksola6o@thetimes.co.uk', '5473423649', 'rD8&=I/!t*X');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (242, 'Saleway', 'Kelsey', 'ksaleway6p@salon.com', '2992443565', 'jQ8@QpAq6.');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (243, 'Gelderd', 'Fredek', 'fgelderd6q@slideshare.net', '7275778285', 'sZ2(`?ZUY');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (244, 'Melrose', 'Livvie', 'lmelrose6r@jiathis.com', '5031178072', 'jS0#QnJG');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (245, 'Machan', 'Carny', 'cmachan6s@eventbrite.com', '8401023583', 'oJ2++Nr2*|<F>=');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (246, 'Chasier', 'Radcliffe', 'rchasier6t@scribd.com', '8955603348', 'mR3&Dk6K`D*aI*m)');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (247, 'Trevenu', 'Zechariah', 'ztrevenu6u@yellowpages.com', '9889753951', 'aO5*ULCA');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (248, 'Ffrench', 'Del', 'dffrench6v@twitter.com', '3428475076', 'mH0.}*"?Qr?qzI');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (249, 'Hentze', 'Anna-maria', 'ahentze6w@qq.com', '7538450317', 'lT9''omxP');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (250, 'Pitkin', 'Franklyn', 'fpitkin6x@google.com.au', '6642874001', 'hZ6\=esQ)fZP');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (251, 'Cowterd', 'Lucy', 'lcowterd6y@fema.gov', '6532344741', 'zB0,IXB)=');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (252, 'McPhelimy', 'Lisle', 'lmcphelimy6z@google.co.jp', '7496230459', 'sQ3,Qxp>Yp');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (253, 'Cino', 'Gennie', 'gcino70@epa.gov', '4742765915', 'aX0/jpYbjMyI6\f');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (254, 'Landsbury', 'Devinne', 'dlandsbury71@scientificamerican.com', '8439107546', 'sV6}\uGi,P+/b4');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (255, 'Zmitrichenko', 'Raddie', 'rzmitrichenko72@skype.com', '4222344940', 'oS7&Vfh@~nFAP+&J');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (256, 'Gosneye', 'Margarita', 'mgosneye73@shutterfly.com', '4328911120', 'eN4}@9/I}VVc');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (257, 'Morden', 'Arnuad', 'amorden74@mozilla.org', '9692970636', 'pM1,flN=pVg<');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (258, 'Elsom', 'Irwinn', 'ielsom75@ocn.ne.jp', '8529311327', 'qA9}pwV_?ks@I603');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (259, 'Blowing', 'Dorey', 'dblowing76@weibo.com', '1111973030', 'tY5\eNp)oJx/');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (260, 'Greenman', 'Micki', 'mgreenman77@homestead.com', '1987480304', 'tH4<''nNQjOAWF?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (261, 'Ivanisov', 'Royce', 'rivanisov78@sina.com.cn', '5811154294', 'yF2{9Knt26O1h''.v');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (262, 'Yeaman', 'Carver', 'cyeaman79@spiegel.de', '4921544757', 'uZ0.qh.5&');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (263, 'Westrope', 'Laurent', 'lwestrope7a@disqus.com', '7402759819', 'vG2\N_y\F)');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (264, 'Ladbrook', 'Ulrika', 'uladbrook7b@ocn.ne.jp', '7837889449', 'lE7&9/k<j/7fNxQ0');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (265, 'Cassley', 'Ian', 'icassley7c@yale.edu', '9699405243', 'mO9)!8ol');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (266, 'Willerson', 'Claiborne', 'cwillerson7d@myspace.com', '9776799318', 'kZ5\DAg7');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (267, 'Rebanks', 'Chane', 'crebanks7e@msn.com', '2054444299', 'jR6{.GXZ{|');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (268, 'Bartram', 'Garold', 'gbartram7f@devhub.com', '3055309000', 'cT7_Bu''Lc');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (269, 'Aland', 'Viv', 'valand7g@elegantthemes.com', '9801152645', 'mT1>}K}Z');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (270, 'Ceaser', 'Iorgos', 'iceaser7h@acquirethisname.com', '7939790139', 'pF5\j''n%9SDwPT');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (271, 'Aylin', 'Teresina', 'taylin7i@ed.gov', '8472131971', 'qK4$FoYKqjffb');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (272, 'Sindell', 'Graham', 'gsindell7j@harvard.edu', '1109433565', 'fH6_tHU+50');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (273, 'Woodfine', 'Maris', 'mwoodfine7k@ftc.gov', '7808848838', 'yS4)qMUHDn1%');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (274, 'Arnould', 'Zacharia', 'zarnould7l@irs.gov', '3506971398', 'rI6''%z"VnTB7/''ry');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (275, 'Goldup', 'Gardener', 'ggoldup7m@mtv.com', '5683002755', 'uY0_YVV}(gfj');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (276, 'Shelly', 'Cornelia', 'cshelly7n@wikispaces.com', '7857858948', 'sV6{_25u{H"<T');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (277, 'Sandells', 'Aila', 'asandells7o@state.tx.us', '4391007496', 'mU6"e)/1Uzp');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (278, 'Benion', 'Connor', 'cbenion7p@dropbox.com', '7191124419', 'pS6%O+UGD5V)6Br');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (279, 'Linley', 'Leelah', 'llinley7q@netvibes.com', '6058303073', 'kA3%"*~''');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (280, 'Yeld', 'Lynette', 'lyeld7r@de.vu', '6556760073', 'yV7/>%74_,');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (281, 'Giamitti', 'Aristotle', 'agiamitti7s@free.fr', '5111937134', 'yP1<2''yKKzlk');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (282, 'Chismon', 'Ibrahim', 'ichismon7t@topsy.com', '1064412622', 'fK4|Xw}WoWsN');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (283, 'Rimmington', 'Sascha', 'srimmington7u@stumbleupon.com', '8893884824', 'kB4"Bi#cI}*%#qT');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (284, 'Redgrave', 'Darell', 'dredgrave7v@archive.org', '6908214119', 'rL4\$/mQqY)EQ#dc');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (285, 'Tiley', 'Maia', 'mtiley7w@google.pl', '7252419751', 'nW6''`,~ILBJ(');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (286, 'Locke', 'Orelie', 'olocke7x@acquirethisname.com', '1655044279', 'sS0<<C!Kt{%');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (287, 'Tweed', 'Maxy', 'mtweed7y@hud.gov', '5031624627', 'hH7\ot_C');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (288, 'Jandac', 'Koren', 'kjandac7z@mit.edu', '1779986506', 'oG8''!@JvvXvKO');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (289, 'McDowall', 'Way', 'wmcdowall80@oracle.com', '1676780372', 'uX1{ReK~pwpm#_<');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (290, 'Kluge', 'Clara', 'ckluge81@xing.com', '9937988022', 'pE0''kF,J3{v');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (291, 'Regardsoe', 'Siffre', 'sregardsoe82@imageshack.us', '9613854915', 'dE2>2Er}0ZZ3I');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (292, 'Paolillo', 'Suzann', 'spaolillo83@marriott.com', '6152960763', 'eV0=Ufy3Vf1');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (293, 'Shee', 'Briny', 'bshee84@virginia.edu', '4222908662', 'nA3`{?~<lnaO@q%7');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (294, 'Brunskill', 'Tisha', 'tbrunskill85@about.me', '4964553215', 'kQ3#Ts6ftD');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (295, 'Troyes', 'Ardelle', 'atroyes86@smugmug.com', '2649880904', 'kL3<fxDV#4');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (296, 'Yerill', 'Adrianne', 'ayerill87@bbc.co.uk', '4654534193', 'sS1%QM"h>@#|@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (297, 'Penzer', 'Lawrence', 'lpenzer88@nyu.edu', '3112006237', 'iQ8"xIi.zLE');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (298, 'McTrustam', 'Katlin', 'kmctrustam89@infoseek.co.jp', '6074843449', 'hM5\L@R+\vt_=#Ll');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (299, 'Hartegan', 'Laurice', 'lhartegan8a@usgs.gov', '2579178089', 'sL3_rI!.jkr7eirt');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (300, 'Vickerstaff', 'Jaquelyn', 'jvickerstaff8b@microsoft.com', '3282835334', 'cS4''0q){<');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (301, 'Doogue', 'Tiphanie', 'tdoogue8c@apple.com', '5583262485', 'xE0|pJ|cX)');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (302, 'Halpine', 'Wit', 'whalpine8d@hostgator.com', '2612457791', 'vB0*BU*AWiUZ3K4*');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (303, 'Rosenstengel', 'Ingrid', 'irosenstengel8e@loc.gov', '4143639850', 'iG0&"M.p?aW=9Yw');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (304, 'Risbridger', 'Kiley', 'krisbridger8f@narod.ru', '6127999626', 'mQ0)#c.Wf,');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (305, 'Whimp', 'Shane', 'swhimp8g@eventbrite.com', '8896235081', 'qB1+%p6NfYU');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (306, 'Featherstonhaugh', 'Perry', 'pfeatherstonhaugh8h@upenn.edu', '3606510550', 'vL4.XhJ0AV');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (307, 'Swinley', 'Mersey', 'mswinley8i@artisteer.com', '4202238656', 'lS4{l.wp`GU&');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (308, 'Roney', 'Klarika', 'kroney8j@flickr.com', '5222188280', 'vQ1`VC''R7');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (309, 'Annion', 'Stace', 'sannion8k@hc360.com', '2894144337', 'qX4EUui~');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (310, 'Calladine', 'Virgie', 'vcalladine8l@gov.uk', '6864488986', 'cG5*~U+5oU|D!u<G');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (311, 'Burnham', 'Vivienne', 'vburnham8m@squarespace.com', '1879249657', 'eF3<7K9k');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (312, 'Orht', 'Paco', 'porht8n@nasa.gov', '9364341281', 'aC9$?)&"');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (313, 'Madre', 'Tristan', 'tmadre8o@github.io', '2143832250', 'lR3+''7htlA&');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (314, 'Stutt', 'Darci', 'dstutt8p@harvard.edu', '4927629675', 'gX4_&NmeE*16');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (315, 'Murden', 'Jolyn', 'jmurden8q@google.pl', '2421257136', 'aX7_\DJ\?1F/');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (316, 'Neale', 'Bret', 'bneale8r@jugem.jp', '8512255808', 'nB0@''x9\Ny');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (317, 'Asipenko', 'Bren', 'basipenko8s@gnu.org', '7978541826', 'tO5=A"%.Mf');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (318, 'Roantree', 'Celle', 'croantree8t@usgs.gov', '2748078541', 'vC3~5D/l\d@"P');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (319, 'Moloney', 'Allys', 'amoloney8u@whitehouse.gov', '5577436417', 'xR4!#BsCRP`');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (320, 'Stooke', 'Jenn', 'jstooke8v@ifeng.com', '3756279619', 'yD8|n6.J4');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (321, 'Clist', 'Shellysheldon', 'sclist8w@bravesites.com', '5893321411', 'vP2%XvAbM+}');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (322, 'Siege', 'Walker', 'wsiege8x@ox.ac.uk', '6682369850', 'jP0?R/UC');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (323, 'Drowsfield', 'Konstantin', 'kdrowsfield8y@soundcloud.com', '6103283245', 'zJ4*JT%A{B\!=V');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (324, 'Aymes', 'Berty', 'baymes8z@amazonaws.com', '7582360302', 'yA5\/KWq');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (325, 'MacKnocker', 'Damian', 'dmacknocker90@google.com.hk', '9345232555', 'wF4)d#V.@fn#6S');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (326, 'Crielly', 'Wendye', 'wcrielly91@netlog.com', '9624430222', 'dK6_Bc&l.z<iU*b');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (327, 'Hamill', 'Ethelin', 'ehamill92@dailymail.co.uk', '8285507448', 'tT2_@DgR1_~');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (328, 'Assur', 'Roscoe', 'rassur93@mail.ru', '8667607960', 'pM7+5#4!rW0YT');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (329, 'Tather', 'Lorena', 'ltather94@narod.ru', '9961499048', 'fL4"_W2vN');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (330, 'Carnock', 'Dene', 'dcarnock95@ehow.com', '6811268227', 'sN6|qo6=$P~C?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (331, 'Jervois', 'Bill', 'bjervois96@elpais.com', '3986094907', 'zA0+6opi5LkOh');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (332, 'Whittingham', 'Gregor', 'gwhittingham97@shinystat.com', '1633314715', 'fA5/*Z_}>');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (333, 'Dietz', 'Glory', 'gdietz98@tinypic.com', '6023602589', 'sJ9\0,RFG|c');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (334, 'Lyne', 'Kynthia', 'klyne99@meetup.com', '1906477650', 'xP3''Cv",2');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (335, 'McVrone', 'Patty', 'pmcvrone9a@wikipedia.org', '8001575044', 'aE4$t$rF!74IBE');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (336, 'Fellis', 'Ginny', 'gfellis9b@google.co.jp', '9084710468', 'dU9)@I6$3');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (337, 'Charters', 'Doralia', 'dcharters9c@vimeo.com', '7034674736', 'oN2<qfIjD{In1N');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (338, 'Drewett', 'Lissa', 'ldrewett9d@ca.gov', '1692661245', 'yR0}LqoQF\u77');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (339, 'Baildon', 'Tabb', 'tbaildon9e@twitter.com', '8347048958', 'nL9)cJzAZ7');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (340, 'McCarlie', 'Lock', 'lmccarlie9f@moonfruit.com', '9721000346', 'eT0*ArCh|>');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (341, 'Magovern', 'Leeann', 'lmagovern9g@cmu.edu', '6593247915', 'wU6)?Tjrs9.ki/D');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (342, 'Aguilar', 'Courtnay', 'caguilar9h@kickstarter.com', '5948529764', 'jB4,WHefxIuH~OuL');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (343, 'Carillo', 'Donal', 'dcarillo9i@jalbum.net', '1496266143', 'uU6>,Cesgr_x9');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (344, 'Drewett', 'Annabell', 'adrewett9j@symantec.com', '4101865677', 'aU6+bQ}#>,~4KXA');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (345, 'Somerton', 'Jerrilee', 'jsomerton9k@rediff.com', '7314531394', 'jX8.xKk,8P5');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (346, 'Stoneham', 'Wylie', 'wstoneham9l@cbsnews.com', '8506418773', 'bZ4~W=C,');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (347, 'Sives', 'Luther', 'lsives9m@mac.com', '8191213045', 'dX6(R\3m/*dj"<H9');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (348, 'Turneaux', 'Roddy', 'rturneaux9n@google.de', '8747759828', 'gM5{0_#*>');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (349, 'Bourley', 'Cherilyn', 'cbourley9o@unesco.org', '4346274821', 'wB1*K2FE');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (350, 'Sleit', 'Harald', 'hsleit9p@msn.com', '5983817549', 'hS1@YYMJau2d');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (351, 'Reynault', 'Wain', 'wreynault9q@github.com', '7999543783', 'kA7>Z3W+');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (352, 'Darbishire', 'Gertrudis', 'gdarbishire9r@com.com', '1002789063', 'zI5(i`eAWk9%M');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (353, 'Goodwin', 'Adelina', 'agoodwin9s@fema.gov', '3802231253', 'eX2.egz/1,s');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (354, 'Borman', 'Bethena', 'bborman9t@zdnet.com', '5833273672', 'jJ1!ZRmG=D6u');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (355, 'Zienkiewicz', 'Jaymee', 'jzienkiewicz9u@senate.gov', '7028100378', 'tV2?6tt}p!');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (356, 'Pietruszka', 'Ange', 'apietruszka9v@biglobe.ne.jp', '4202346858', 'gT9_`J66&q');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (357, 'Sawforde', 'Skip', 'ssawforde9w@youtu.be', '7336875652', 'lF7?\A\&?+CL');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (358, 'Gourlay', 'Charlton', 'cgourlay9x@wikipedia.org', '3019345480', 'yI2%$nonVqBcL*');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (359, 'Bennetto', 'Cherice', 'cbennetto9y@nhs.uk', '1252204603', 'cupcak3!');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (360, 'Skeleton', 'Grove', 'gskeleton9z@ifeng.com', '3585962703', 'yR4Ix<qy*M');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (361, 'Bidwell', 'Josefina', 'jbidwella0@hexun.com', '9273362769', 'hN9XsC$3@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (362, 'Halfhide', 'Nicola', 'nhalfhidea1@mozilla.com', '5468721338', 'bN9/zhJxHBr');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (363, 'Spira', 'Laurie', 'lspiraa2@flickr.com', '2969796744', 'lL4~sioM&(~j8');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (364, 'Orro', 'Horst', 'horroa3@sakura.ne.jp', '5921817468', 'kI0<uv}Q=DGls');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (365, 'List', 'Maddy', 'mlista4@paginegialle.it', '6454102603', 'yD5Veh*#oa');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (366, 'Iskow', 'Arlyne', 'aiskowa5@de.vu', '6691700708', 'jJ2>gF)#ThTMT');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (367, 'Eastcott', 'Isadore', 'ieastcotta6@ftc.gov', '2199262442', 'qK7}(~}XOw');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (368, 'Jeandel', 'Blanche', 'bjeandela7@dropbox.com', '5364177351', 'sY4b)llG');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (369, 'Klyner', 'Kain', 'kklynera8@theatlantic.com', '4627765858', 'qA2fVVrM');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (370, 'Broadey', 'Godwin', 'gbroadeya9@w3.org', '6784734543', 'uO1!By%k@');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (371, 'Bertholin', 'Buckie', 'bbertholinaa@ifeng.com', '2097990112', 'uX6#<gB#0IE9kQJ');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (372, 'Tuxsell', 'Orly', 'otuxsellab@harvard.edu', '2135434318', 'cT7&+0)S');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (373, 'Ghent', 'Melvyn', 'mghentac@fc2.com', '1891607380', 'qD9`DwkT');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (374, 'Abdie', 'Nobe', 'nabdiead@godaddy.com', '1214639490', 'jG7*k2%X!Oos');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (375, 'Birtonshaw', 'Janenna', 'jbirtonshawae@nifty.com', '8185329692', 'vB1\8A!DeN51Z51');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (376, 'Rozalski', 'Crichton', 'crozalskiaf@imageshack.us', '1621435350', 'eG4#~PoK');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (377, 'O''Hallihane', 'Karyn', 'kohallihaneag@discovery.com', '6637472552', 'oW6<mdqca+/Vhz');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (378, 'Grent', 'Mitch', 'mgrentah@redcross.org', '8795919501', 'mY2#l2j{VWM9+e');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (379, 'Matignon', 'Baxter', 'bmatignonai@1und1.de', '3272432064', 'kN2=T5n7YQ@L');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (380, 'Grinikhin', 'Rosalinda', 'rgrinikhinaj@nydailynews.com', '1106371150', 'qO1>!VA+_&%+r');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (381, 'Sydry', 'Nadine', 'nsydryak@vkontakte.ru', '1918256766', 'tB1}<JL/8{khg?');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (382, 'Spinks', 'Michele', 'mspinksal@theglobeandmail.com', '3439847162', 'hA5(s~ubS6');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (383, 'Jozsa', 'Goldy', 'gjozsaam@state.tx.us', '6505865686', 'xB9?j%Zh=69mVA');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (384, 'Sawden', 'Breena', 'bsawdenan@netvibes.com', '2472128586', 'hL1>d$h5p003P/>');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (385, 'Strasse', 'Kiersten', 'kstrasseao@ted.com', '9568897692', 'tF3}v1o+');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (386, 'Garrigan', 'Allyn', 'agarriganap@ibm.com', '4077519373', 'hE1\*cS');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (387, 'Dinsdale', 'Anthia', 'adinsdaleaq@ox.ac.uk', '2985415220', 'qH5%Chrujjb');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (388, 'Klimsch', 'Fitz', 'fklimschar@ed.gov', '3512730467', 'vF2$Xq3xNFbn');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (389, 'Dudderidge', 'Timoteo', 'tdudderidgeas@booking.com', '2857328949', 'sL3/R{Z$OLx>5J');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (390, 'Supple', 'Roseann', 'rsuppleat@cafepress.com', '4918419165', 'fG8%=8Ro%bjn{)');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (391, 'Sorsby', 'Candida', 'csorsbyau@skyrock.com', '7181052539', 'cD7TuLCFXJqALLl');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (392, 'Bottini', 'Trudie', 'tbottiniav@eventbrite.com', '7683653168', 'vO8/Os_iyy7fx~Z');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (393, 'White', 'Gay', 'gwhiteaw@twitpic.com', '1964748912', 'dN9)L$A~(+sT=W');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (394, 'Shurey', 'Allan', 'ashureyax@foxnews.com', '3653019705', 'xJ3{uNeWc5ccis');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (395, 'Inwood', 'Fanni', 'finwooday@examiner.com', '6927458779', 'aU0+mY/gOfd');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (396, 'Harsent', 'Ulick', 'uharsentaz@sohu.com', '3334869102', 'hZ4@ss6~RKO$');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (397, 'Brierton', 'Fonsie', 'fbriertonb0@spiegel.de', '3539325369', 'tK0}yTXi');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (398, 'Alloisi', 'Coop', 'calloisib1@devhub.com', '1172863906', 'iB9@ulDoS_');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (399, 'Dumbreck', 'Giordano', 'gdumbreckb2@aboutads.info', '8262702374', 'gA2|z*n=iLS=fD');
insert into GUEST (GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD) values (400, 'Astlet', 'Kattie', 'kastletb3@newyorker.com', '9781071587', 'vP8|b!G3');



SELECT *
FROM GUEST;

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (100, '2025-04-17', '2025-04-18', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (101, '2025-04-18', '2025-04-19', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (102, '2025-04-19', '2025-04-20', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (103, '2025-04-21', '2025-04-22', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (102, '2025-04-19', '2025-04-21', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (104, '2025-04-24', '2025-04-25', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (107, '2025-04-25', '2025-04-26', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (105, '2025-06-25', '2025-06-29', 1, 100);
INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (106, '2025-06-25', '2025-06-29', 1, 102);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (108, '2025-04-26', '2025-04-27', 1, 102);
INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (109, '2025-04-26', '2025-04-27', 1, 100);
INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES(110, '2025-04-25', '2025-04-28', 1, 105);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES(111, '2025-04-26', '2025-04-29', 1, 106);

SELECT *
FROM STAY
WHERE (STAY_CHECKIN_DATE >= '2025-05-31T04:00:00.000Z' 
OR STAY_CHECKOUT_DATE = '2025-06-02T04:00:00.000Z')
AND STAY_IS_CANCELED = 0;


SELECT *
FROM ROOM;
WHERE STAY_ID IS NOT NULL;

insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (1, 'Heinzler', 'Nomi', 'nheinzler0@pcworld.com', '1132570194', 'tM9}lt~=XC', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (2, 'Bethel', 'Kassi', 'kbethel1@w3.org', '8338210967', 'lU3|RNI+C5ydLW', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (3, 'Reddell', 'Valera', 'vreddell2@tinypic.com', '7165506922', 'sA8!Ffn%F!V.p%', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (4, 'Castellaccio', 'Sherie', 'scastellaccio3@foxnews.com', '9065889988', 'eG2{FX5(', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (5, 'Clohissy', 'Casey', 'cclohissy4@angelfire.com', '1623918636', 'dD2}+|P!"HE', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (6, 'Beccera', 'Isiahi', 'ibeccera5@com.com', '6253480643', 'gW3&7u)S5*R%!2Pb', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (7, 'Dowrey', 'Brennan', 'bdowrey6@boston.com', '2133251549', 'xK6&iO7vPUG?`kH{', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (8, 'Longhi', 'Yoko', 'ylonghi7@scribd.com', '7183020956', 'rG3)Z1#)@Vo5_G', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (9, 'Pidgen', 'Luciano', 'lpidgen8@godaddy.com', '8101690436', 'cK6$h}xs|?', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (10, 'McComas', 'Arlen', 'amccomas9@barnesandnoble.com', '6064222861', 'eQ8#1kZ%{s1WjP', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (11, 'Cumbers', 'Winnah', 'wcumbersa@w3.org', '7438892706', 'qO9*EUB5mI(ivn', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (12, 'Hellin', 'Rodrick', 'rhellinb@arizona.edu', '8309763983', 'mF2{@#ituO/@ueZ%', 1);
insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_LNAME, EMPLOYEE_FNAME, EMPLOYEE_EMAIL, EMPLOYEE_PHONE, EMPLOYEE_PASSWORD, PROPERTY_ID) values (13, 'Sallese', 'Michaela', 'msallese01@southhills.edu', '8309763983', 'password', 1);



UPDATE STAY
SET STAY_IS_CANCELED = 1;

SELECT COUNT(DISTINCT `room`.`ROOM_ID`)
FROM `ROOM` `room` LEFT JOIN `STAY` `stay` ON `stay`.`STAY_ID`=`room`.`STAY_ID` 
WHERE (`stay`.`STAY_CHECKIN_DATE` >= '2025-05-31T04:00:00.000Z'
OR `stay`.`STAY_CHECKOUT_DATE` <= '2025-05-31T04:00:00.000Z'
OR `room`.`STAY_ID` IS NULL);


SELECT *
FROM `STAY` `stay` 
LEFT JOIN `ROOM` `room` ON `room`.`STAY_ID`=`stay`.`STAY_ID`
UNION 
SELECT *
FROM `ROOM` `room`
RIGHT JOIN `STAY` `stay` ON `room`.`STAY_ID`=`stay`.`STAY_ID`
 WHERE `stay`.`STAY_CHECKIN_DATE` >= '2025-05-31T04:00:00.000Z' AND `stay`.`STAY_CHECKOUT_DATE` = '2025-05-31T04:00:00.000Z'
 AND (`stay`.`STAY_CHECKIN_DATE` = '2025-05-31T04:00:00.000Z' AND `room`.`STAY_ID` IS NULL);


 SELECT *
 FROM STAY
 WHERE STAY_IS_CHECKED_IN = 1
 AND STAY_IS_CANCELED = 0;


 SELECT *
 FROM GUEST
 WHERE GUEST_ID = 407;


UPDATE ROOM
SET ROOM_IS_BLOCKED = 0
WHERE STAY_ID IS NULL;

 SELECT *
 FROM STAY;

SELECT *
FROM CREDIT_CARD;


SELECT *
FROM ROOM;

SELECT *
FROM STAY;

UPDATE STAY
SET STAY_IS_CHECKED_IN = 0
WHERE STAY_ID NOT IN (181, 182, 183, 184, 185);

SELECT COUNT(1) AS `cnt` FROM `STAY` `stay` 
WHERE (`stay`.`STAY_CHECKIN_DATE` >= "2025-06-01T04:00:00.000Z" OR `stay`.`STAY_CHECKOUT_DATE` = "2025-06-01T04:00:00.000Z") 
AND `stay`.`STAY_IS_CANCELED` = 0
AND (`stay`.`STAY_IS_CHECKED_IN` = 1 or `stay`.`STAY_IS_CHECKED_IN` is null);


SELECT COUNT(1) AS `cnt` FROM `STAY` `stay` WHERE (`stay`.`STAY_CHECKIN_DATE` >= "2025-05-31T04:00:00.000Z" OR `stay`.`STAY_CHECKOUT_DATE` = "2025-06-01T04:00:00.000Z") AND `stay`.`ROOM_TYPE`
 = 'K' AND `stay`.`STAY_IS_CANCELED` = 0;

 SELECT COUNT(1) AS `cnt` FROM `STAY` `stay` WHERE (`stay`.`STAY_CHECKIN_DATE` >= "2025-05-31T04:00:00.000Z" OR `stay`.`STAY_CHECKOUT_DATE` = "2025-06-01T04:00:00.000Z") AND `stay`.`ROOM_TYPE`
 = 'Q' AND `stay`.`STAY_IS_CANCELED` = 0;

