-- CREATE SCHEMA StayComm;

USE StayComm;

CREATE TABLE GUEST(
    GUEST_ID    INT UNSIGNED,
    GUEST_LNAME VARCHAR(64) NOT NULL,
    GUEST_FNAME VARCHAR(64) NOT NULL,
    GUEST_EMAIL VARCHAR(64) NOT NULL,
    GUEST_PHONE CHAR(10) NOT NULL,
    GUEST_PASSWORD  VARCHAR(64) NOT NULL,
    PRIMARY KEY (GUEST_ID)
);


CREATE TABLE CREDIT_CARD(
    CREDIT_CARD_ID  INT UNSIGNED,
    CREDIT_CARD_NUM     CHAR(16) NOT NULL,
    CREDIT_CARD_EXP_DATE    DATE NOT NULL,
    CREDIT_CARD_CVV     CHAR(3) NOT NULL,
    GUEST_ID    INT UNSIGNED NOT NULL,
    PRIMARY KEY (CREDIT_CARD_ID),
    FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID)
);

CREATE TABLE PROPERTY(
    PROPERTY_ID INT UNSIGNED,
    PROPERTY_NAME VARCHAR(64) NOT NULL,
    PROPERTY_STREET_ADDR VARCHAR(64) NOT NULL,
    PROPERTY_CITY VARCHAR(64) NOT NULL,
    PROPERTY_STATE CHAR(2) NOT NULL,
    PROPERTY_KING_ROOMS INT UNSIGNED NOT NULL,
    PROPERTY_QUEEN_ROOMS INT UNSIGNED NOT NULL,
    PRIMARY KEY (PROPERTY_ID)
);

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT UNSIGNED,
    EMPLOYEE_LNAME  VARCHAR(64) NOT NULL,
    EMPLOYEE_FNAME  VARCHAR(64) NOT NULL,
    EMPLOYEE_EMAIL  VARCHAR(64) NOT NULL,
    EMPLOYEE_PHONE  CHAR(10) NOT NULL,
    EMPLOYEE_PASSWORD   VARCHAR(64) NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

CREATE TABLE STAY(
    STAY_ID INT UNSIGNED,
    STAY_CHECKIN_DATE DATE NOT NULL,
    STAY_CHECKOUT_DATE DATE NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    GUEST_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (STAY_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID)
);

CREATE TABLE ROOM(
    ROOM_ID INT UNSIGNED,
    ROOM_TYPE CHAR(1) NOT NULL,
    ROOM_IS_CLEAN BOOLEAN NOT NULL,
    ROOM_IS_BLOCKED BOOLEAN NOT NULL,
    STAY_ID INT UNSIGNED,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ROOM_ID),
    FOREIGN KEY (STAY_ID) REFERENCES STAY(STAY_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

ALTER TABLE STAY
ADD ROOM_ID INT UNSIGNED;

ALTER TABLE STAY
ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);

CREATE TABLE RATE(
    RATE_ID VARCHAR(5),
    RATE_PRICE DECIMAL(7,2) UNSIGNED NOT NULL DEFAULT (99.0),
    RATE_DATE DATE NOT NULL,
    STAY_ID INT UNSIGNED,
    PRIMARY KEY (RATE_ID),
    FOREIGN KEY (STAY_ID) REFERENCES STAY(STAY_ID)
);

DROP TABLE RATE;


INSERT INTO PROPERTY (PROPERTY_ID, PROPERTY_NAME, PROPERTY_STREET_ADDR, PROPERTY_CITY, PROPERTY_STATE, PROPERTY_KING_ROOMS, PROPERTY_QUEEN_ROOMS)
VALUES(1, 'Nickhill Suites', '100 Nicks House Lane', 'Nickville', "NP", 50, 50);

INSERT INTO GUEST(GUEST_ID, GUEST_LNAME, GUEST_FNAME, GUEST_EMAIL, GUEST_PHONE, GUEST_PASSWORD)
VALUES(100, 'Thegreat', 'Valtor', 'valtor@great.com', '4128675309', 'h00lah00ps');

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (100, '2025-04-17', '2025-04-18', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (101, '2025-04-18', '2025-04-19', 1, 100);

INSERT INTO STAY (STAY_ID, STAY_CHECKIN_DATE, STAY_CHECKOUT_DATE, PROPERTY_ID, GUEST_ID)
VALUES (102, '2025-04-19', '2025-04-20', 1, 100);


INSERT INTO RATE(RATE_ID, RATE_DATE, STAY_ID)
VALUES(REG1, '' )

SELECT *
FROM STAY;